SPELLS_MODULE_CHECK_ID1 = 1
SPELLS_MODULE_CHECK_ID2 = 2
SPELLS_MODULE_CHECK_ID3 = 3
SPELLS_MODULE_CHECK_ID4 = 4
SPELLS_MODULE_CHECK_ID5 = 4
ITEM_EXCHANGE_MODULE_ID = 10

NPC_QUEST_MODULE_CHECK_ID = 42
NPC_TRADE_MODULE_CHECK_ID = 500



----- dialogue CHECK Ids start at 1000

DIA_BRYAN_BANDITHEADS_CHECKID = 1000
